### ISSUE TITLE
dwarf dump using class in place of struct

### ISSUE THREAD

**Issue by rickhen85** [encounter/decomp-toolkit#10]
I've noticed that dwarf dump are setting classes as structs and structs as classes. Apparently in struct and class members it's defining in the right way. Here's an example:
![image](https://github.com/encounter/decomp-toolkit/assets/126277594/ffadebee-f71b-4ee9-82fd-dda2dca09c5d)

**Comment by encounter** [comment]
```rust
        StructureKind::Struct => "class".to_string(),
        StructureKind::Class => "struct".to_string(),
```
Well, at least it was simple!
