### ISSUE TITLE
Fail to split dol when symbols are applied

### ISSUE THREAD

**Issue by SwareJonge** [encounter/decomp-toolkit#20]
dtk fails to split all versions Inazuma Eleven Strikers when symbols are applied.

With symbols_known turned off the analyzer doesn't seem to know these functions are local
```
Failed: While loading object 'main.dol'

Caused by:
    Multiple symbols with name longlong2str: 11989 Function 0x801E7D10 and 12018 Function 0x801EAC5C
```

Enabling `symbols_known` causes a cyclic dependency error (also on local functions it seems)
```
Failed: While processing object 'main.dol' (module ID 0)

Caused by:
    Cyclic dependency (involving auto_load_match_tex__Fv_text) encountered while resolving link order
```
repo can be found [here](https://github.com/SwareJonge/iestrikers-dtk)

**Comment by encounter** [comment]
This will be fixed in v0.7.0.

Here's the configuration I used while testing: [STQJHF.zip](https://github.com/encounter/decomp-toolkit/files/13852311/STQJHF.zip)
