### ISSUE TITLE
Issue with splitting RELs

### ISSUE THREAD

**Issue by TakaRikka** [encounter/decomp-toolkit#45]
trying to split tp debug RELs (without using map option), it fails on certain RELs. 
![image](https://github.com/encounter/decomp-toolkit/assets/38417346/a9b5bbb4-b3c2-4ae2-b7ed-5149a93aee5e)

**Comment by encounter** [comment]
Do you happen to have `quick_analysis: true` set in `config.yml`? If so, that should be removed.

**Comment by TakaRikka** [comment]
no, but i did accidentally leave `symbols_known: true`. setting it to false fixed it
