### ISSUE TITLE
[BUG] dwarf dump does not understand anonymous unions. 

### ISSUE THREAD

**Issue by ProfElements** [encounter/decomp-toolkit#46]
### Game Name

Spongebob Squarepants: Creature from the Krusty Krab

### Game Version

USA V0

### Description

When I run `dwarf dump` the structures are not populated correctly. Instead of being able to parse the struct, they get hit by and anonymous union at the tail end of it. 

I did a simple fix by changing `src/util/dwarf.rs` line `1838` and changing it from `let name = name.ok_or_else(|| anyhow!("Member without name: {:?}", tag))?;` to `let name = name.unwrap_or("".to_string());` 

I don't think that is a good fix but it did it for me. I think there might need to be a more specific fix for this.

**Comment by encounter** [comment]
I worked through all of the errors that occurred when `dwarf dump`-ing CFKK, so the output should be much more complete now!
