### ISSUE TITLE
[BUG] Failed to analyze SSBB

### ISSUE THREAD

**Issue by wowjinxy** [encounter/decomp-toolkit#47]
### Repository URL

https://github.com/wowjinxy/dtk-brawl

### Game Name

Super Smash Brothers Brawl

### Game Version

RSBE01

### Description

E:\dtk-brawl>ninja
[1/3] TOOL build\tools\dtk.exe
Downloading https://github.com/encounter/decomp-toolkit/releases/download/v0.7.5/dtk-windows-x86_64.exe to build\tools\dtk.exe
[2/3] SPLIT config\RSBE01\config.yml
FAILED: build/RSBE01/config.json
build\tools\dtk.exe dol split config\RSBE01\config.yml build\RSBE01
 INFO Loading config\RSBE01\config.yml
 INFO Loading and analyzing 127 modules (using 16 threads)
ERROR module{name=sora_scene}: Failed to finalize functions:
ERROR module{name=sora_scene}:   0:0x000221D0
ERROR module{name=sora_scene}:   0:0x00022D3C
ERROR module{name=sora_scene}:   0:0x000234F4
ERROR module{name=sora_scene}:   0:0x0002442C
ERROR module{name=sora_scene}:   0:0x00024BA0
ERROR module{name=sora_scene}:   0:0x00032C3C
ERROR module{name=sora_scene}:   0:0x00036990
ERROR module{name=sora_scene}:   0:0x0003B16C
ERROR module{name=sora_scene}:   0:0x0003C26C
ERROR module{name=sora_scene}:   0:0x0003CFC8
Failed: While loading object 'main.dol'

Caused by:
    Overlapping functions 3:0x802F7728-3:0x802F7910 -> 3:0x802F7ninja: error: rebuilding 'build.ninja': subcommand failed
744

**Comment by encounter** [comment]
Fixes included in v0.7.6. PR here: https://github.com/wowjinxy/dtk-brawl/pull/1
