### ISSUE TITLE
[ISSUE] Multiple sections with name .rodata

### ISSUE THREAD

**Issue by Surasia** [encounter/decomp-toolkit#49]
### Game Name

Wii Sports Resort

### Game Version

USA v1.1

### Description

While trying to analyze the game, I get the error of "Multiple sections with name .rodata". From what I understand, the dol file has a duplicate segment with the same name, but looking at it in IDA it seems like both contain different data. Is there any possible way of specifying the segment it should use?

**Comment by encounter** [comment]
Yes, the generated splits.txt will show the multiple `.rodata` sections. For Wii Sports Resort, one of these sections is likely a `.BINARY` section. You can rename it in splits.txt and then **remove** symbols.txt to have it regenerate.
