### ISSUE TITLE
[BUG] Handwritten addresses are interpreted as pointers

### ISSUE THREAD

**Issue by Yanis42** [encounter/decomp-toolkit#52]
### Repository URL

https://github.com/Yanis42/oot-gc-dtk

### Game Name

Zelda: Ocarina of Time - Master Quest and Collector's Edition N64 Emulator

### Game Version

Any

### Description

dtk is interpreting N64 addresses written in code as pointers, this makes the assembly harder to understand once decompiled (and it's giving a fake diff), the current workaround is to use ``noreloc`` (which is what I used on the ``systemSetupGameALL`` symbol)

to find these addresses in the source files you can look for calls of ``cpuSetCodeHack``

**Comment by encounter** [comment]
In [release v0.8.3](https://github.com/encounter/decomp-toolkit/releases/tag/v0.8.3), the `block_relocations` option was added.
