### ISSUE TITLE
Skip Invalid Instructions

### ISSUE THREAD

**Issue by NWPlayer123** [encounter/decomp-toolkit#55]
Just Dance 2 (Best Buy Edition), along with presumably any game using MetaFortress, deliberately create invalid instructions as an anti-piracy measure. Currently, dtk hard-fails when encountering an invalid instruction, such as when splitting out the dol. Instead, it should silently ignore invalid instructions and continue with analysis.

**Comment by Rainchus** [comment]
As discussed in the discord, this symbol for a different architecture gets linked into mario parties 5-7, which cant be properly disassembled and therefore cannot created a matching rel file https://github.com/Rainchus/mp7-dtk/blob/8ba9802f589c89029be0fcecc486e0b4279172bc/config/dll/rels/m755dll/symbols.txt#L97
