### ISSUE TITLE
Mention degree of Wii U support

### ISSUE THREAD

**Issue by rrika** [encounter/decomp-toolkit#66]
Could you clarify in the README to what degree this workflow is applicable to Wii U? In the middle it is mentioned that the Wii U disc format is supported, but that's far from the whole flow.

Thank you!

**Comment by encounter** [comment]
Hi! Wii U isn’t supported at all, it uses a totally different toolchain, different SDK and different formats. 

The mention of Wii U is for Wii Virtual Console titles: they contain the underlying Wii game disc image in a special format (.nfs) that this supports extracting.

**Comment by rrika** [comment]
thanks!
