### ISSUE TITLE
Dtk tries to disassemble data as code in certain situations

### ISSUE THREAD

**Issue by Rainchus** [encounter/decomp-toolkit#7]
In the GC mario party games, there is a branch to every .text symbol in a giant list to make the symbols visible to the rels. When dtk encounter this, it throws an error about trying to disassemble data as code

**Comment by InputEvelution** [comment]
This also occurs when attempting to analyse the rels for SADX's demo versions.

**Comment by encounter** [comment]
This is now fixed in v0.6.0. The analyzer will ignore jumps to data sections rather than considering it an error.
