### ISSUE TITLE
[BUG] VFS doesn't support map files

### ISSUE THREAD

**Issue by NWPlayer123** [encounter/decomp-toolkit#77]
### Description

In addition to the dtk v1.1 release not supporting Windows paths (this seems to be fixed in main), it also doesn't support map files from config.yml which means any game has to have the extracted fs on first setup

**Comment by encounter** [comment]
`map` key isn't relative to `object_base`, since it's basically one time use. But you can use a project-relative VFS path if desired: `orig/GAMEID/game.rvz:files/foo.map`
