### ISSUE TITLE
Failed: Unhandled user defined type ClassType and Failed: Unhandled ClassType child Inheritance

### ISSUE THREAD

**Issue by rickhen85** [encounter/decomp-toolkit#8]
When I try to do a `dtk dwarf dump` on FIFA_d.elf from FIFA2004 Gamecube I get the error `Failed: Unhandled user defined type ClassType`. I've tried to create the class type, and that fixed the error, but when i tried the command again i got the error `Failed: Unhandled ClassType child Inheritance`

**Comment by encounter** [comment]
This is fixed in v0.6.0, which overhauls `dwarf dump` for C++ support.
